### ISSUE TITLE
Feature request: Kline

### ISSUE THREAD

**Issue by lispc** [Fluidex/dingir-exchange#1]
We need to implement kline API. 

Parameters:

Name | Type | Mandatory | Description
-- | -- | -- | --
market | STRING | YES |  
interval | ENUM | YES |  
startTime | LONG | NO |  
endTime | LONG | NO |  
limit | INT | NO | Default 500; max 1000.

Result example:

```
[
  [
    1499040000000,      // Open time
    "0.01634790",       // Open
    "0.80000000",       // High
    "0.01575800",       // Low
    "0.01577100",       // Close
    "148976.11427815",  // Volume
    "2434.19055334",    // Quote asset volume
  ]
]
```

This can be implemented by time series db.

Timescaledb: [example](https://github.com/LoopringSecondary/lightcone_legacy/blob/28142a7862dec33f79fa18e0ed2a8faae72604dc/persistence/src/main/scala/io/lightcone/persistence/dals/OHLCDataDalImpl.scala#L105)

OR 

Influxdb example [Read](https://github.com/openware/peatio/blob/2d0a0bc0718f35b18753cc3eaeab6fe06ea58ef5/app/services/k_line_service.rb#L40) and [Write](https://github.com/openware/peatio/blob/2d0a0bc0718f35b18753cc3eaeab6fe06ea58ef5/app/models/trade.rb#L18)

We need a separate daemon process which fetches trades from Kafka then inserts them into the time series db.

This feature depends the REST API server in <https://github.com/Fluidex/dingir-exchange/issues/5>

**Comment by lispc** [comment]
it may worth 500-600 usd ?

**Comment by noel2004** [comment]
So the work should include:

1. A daemon (aka. a bin) which consume the trades topic and put the trade messages into timescaledb

   *How do we consider about the current trade_history table in pg? Is it of no use and should be removed?*

   *Or we just migrate the db_history into timescaledb, and provide different ways for recording history (dumping them directly from matching engine, or just persist them into kafka, then dump the data in another consumer daemon?*

2. A module (kline manager in current feature/kline branch) providing query for k-line in different time-scale (commonly, in minute/hour/day/week)

Above should be a 20-25hrs work. Most time may be spent on writing and testing the correct query for reading and aggregating the data for k-line from db. With some more time an API can be also added to server (#5).

**Comment by noel2004** [comment]
Upate: the output kline data should fit into an API request like

https://zlq4863947.gitbook.io/tradingview/3-shu-ju-bang-ding/udf

The implement has been illustrated when resolve #40

**Comment by noel2004** [comment]
Plan to strip part of the trade messages into a new table like:

``` sql

-- Add migration script here

CREATE TABLE trade_record (
    time TIMESTAMP(0) NOT NULL,
    market VARCHAR(30) NOT NULL,
    trade_id BIGINT CHECK (trade_id >= 0) NOT NULL,
    price DECIMAL(30, 8) NOT NULL,
    amount DECIMAL(30, 8) NOT NULL,
);

CREATE INDEX trade_record_idx_market ON trade_record (market, time DESC);

SELECT create_hypertable('trade_record', 'time');

```

Though duplicated to the trade_history table I think this is a suitable designation.

**Comment by noel2004** [comment]
https://github.com/noel2004/dingir-exchange/commit/83fc4245c5098f7536824015db68ff0cb029cb08

The query part is almost done ("next_time" indication left)

**Comment by HAOYUatHZ** [comment]
> [noel2004@83fc424](https://github.com/noel2004/dingir-exchange/commit/83fc4245c5098f7536824015db68ff0cb029cb08)
> 
> The query part is almost done ("next_time" indication left)

great I will take a look today

**Comment by HAOYUatHZ** [comment]
Looks no big issue.

1. "trade_record" and "trade_history" names are too similar, and thus can be confusing. I may look into namings in other project once I have time.
2. will keeping naming "first, last, max, min, sum" consistent with "open, close, high, low, volume"  in https://github.com/Fluidex/dingir-exchange/blob/92a4aca073f042eabf692ed93b329661b2944a64/src/restapi/types.rs#L11 be better?

**Comment by lispc** [comment]
It seems better to use serde derive rename rather than my comments hahah

**Comment by noel2004** [comment]
https://github.com/noel2004/dingir-exchange/commit/d8ef6808970c112dbf8cc6b078c0e53c5ee39d16

Now I finish the query part.

I have made fields in RPCError public, should be reasonable?

**Comment by noel2004** [comment]
> Looks no big issue.
> 
> 1. "trade_record" and "trade_history" names are too similar, and thus can be confusing. I may look into namings in other projects once I have time.
> 2. will keeping naming "first, last, max, min, sum" consistent with "open, close, high, low, volume"  in https://github.com/Fluidex/dingir-exchange/blob/92a4aca073f042eabf692ed93b329661b2944a64/src/restapi/types.rs#L11-L19
>     be better?

I just too lazy to add an "as xxx" alias instruction into my sqlquery :P .... The naming in KlineItem has no matter with the outputing serialize and can be changed in arbitrary.

**Comment by HAOYUatHZ** [comment]
close via https://github.com/Fluidex/dingir-exchange/pull/45
