### ISSUE TITLE
fix: persist did not use batch insert

### ISSUE THREAD

**Issue by lispc** [Fluidex/dingir-exchange#109]
<https://github.com/Fluidex/dingir-exchange/blob/4b18bc6e91bd605e3953b4a970b5b96ee300a13a/src/matchengine/persist.rs#L254>

<https://github.com/Fluidex/dingir-exchange/blob/4b18bc6e91bd605e3953b4a970b5b96ee300a13a/src/matchengine/persist.rs#L300>

and also add `dump_to_db ` time cost to <https://github.com/Fluidex/dingir-exchange/blob/4b18bc6e91bd605e3953b4a970b5b96ee300a13a/src/matchengine/persist.rs#L428>

**Comment by HAOYUatHZ** [comment]
closed via #125
