### ISSUE TITLE
feature: ordered msg

### ISSUE THREAD

**Issue by lispc** [Fluidex/dingir-exchange#114]
the rollup module need **strong ordered** event log ( at least balance update and trade ) to replay like this

<https://github.com/Fluidex/circuits/blob/master/test/testdata/msgs_float.jsonl> 

Currently I generated this replay log like this

<https://github.com/Fluidex/dingir-exchange/blob/99705b4abc1cb6acd0283f6e749e2da4e2740c40/src/matchengine/market.rs#L961>

in the future, the rollup module need to know replay log like this, so we may need to write mq msgs to the same topic to keep order? ( can kafka keep order? we'd better add a global sequence event msg id, so even one day kafka goes out of order, the rollup module can reorder these msgs or at least die loudly... ) 

We may need to unify BalancePersistor and TradePersistor struct.

When finishing this feature, we need to add a test: a js script fetches data from mq and then write the msgs to a `msgs_float.jsonl` file.

**Comment by noel2004** [comment]
The DatabaseWriter can persist records by completely ordered: When create an DatabaseWriter object, simply set spawn_limit to 1 in DatabaseWriterConfig. We may lost some performance but not significant.

On the other hand, kafka can not keep the record be strong ordering unless we set the partition into 1 and lost all the scalability. It seems not so acceptable. Or we have to find a way in which a "partitional" ordering can be applied, that is, event can be sharded and they are ordered in a single shard.

**Comment by noel2004** [comment]
Build the full ordering record base on a kafka topic has 1 partition seems dead simple: we could just use current implement to write all the messages into same topic instead of three, with message key for distinguishing. We even need not to do more wrapping on them.

**Comment by noel2004** [comment]
> Build the full ordering record base on a kafka topic has 1 partition seems dead simple: we could just use current implement to write all the messages into same topic instead of three, with message key for distinguishing. We even need not to do more wrapping on them.

Well not so easy if we dig into the detail of implement in rdkafka. One issues is when "send" method in produce has been successfully called, the message is just queued in localhost and there is no insurance that it must be persisted onto remote host. To obtain a robust record persisting we may have to made more code like checking the delivery report ...

**Comment by lispc** [comment]
> > Build the full ordering record base on a kafka topic has 1 partition seems dead simple: we could just use current implement to write all the messages into same topic instead of three, with message key for distinguishing. We even need not to do more wrapping on them.
> 
> Well not so easy if we dig into the detail of implement in rdkafka. One issues is when "send" method in produce has been successfully called, the message is just queued in localhost and there is no insurance that it must be persisted onto remote host. To obtain a robust record persisting we may have to made more code like checking the delivery report ...

So we may not rely kafka and it's client lib.  Another option is to add a global seq id into message ，and process this seq id in the consumer side

**Comment by lispc** [comment]
Relying rdkafka implementation details seems to dangerous

**Comment by noel2004** [comment]
> > > Build the full ordering record base on a kafka topic has 1 partition seems dead simple: we could just use current implement to write all the messages into same topic instead of three, with message key for distinguishing. We even need not to do more wrapping on them.
> > 
> > 
> > Well not so easy if we dig into the detail of implement in rdkafka. One issues is when "send" method in produce has been successfully called, the message is just queued in localhost and there is no insurance that it must be persisted onto remote host. To obtain a robust record persisting we may have to made more code like checking the delivery report ...
> 
> So we may not rely kafka and it's client lib. Another option is to add a global seq id into message ，and process this seq id in the consumer side

Well not so serious. Unless we really need a "one request, one confirm" scheme, we can still achieve a ordering and data-safety implement even by kafka (1 partition topic) and its client in some extend:

1. Specify "never timeout" when sending message so the client never drop a message from its inside queue because of timeout
2. Use deliver report to calculate current size of client's queue (the default maximum is ~10000) and mark service is not available when water level is high.
3. Grace-exit scheme which ensure the inside queue is empty on process exiting.
3. By these efforts, we can keep the lost limited (we missed data only  if matching engine crashed)
