### ISSUE TITLE
use other logger instead

### ISSUE THREAD

**Issue by HAOYUatHZ** [Fluidex/dingir-exchange#115]
according to @driftluo

> env_logger should never be used in async runtime
> env_logger uses os std writer, which comes with locks
> whereas Future in async runtime is non-blocking
> this will probably lead to blocking executor thread
> if you use env_logger for multi-thread, you may encouter many strange bugs including waker non-functioning

**Comment by lispc** [comment]
<https://github.com/tokio-rs/tracing> may work

**Comment by driftluo** [comment]
> > @lispc tracing is better for event trace，but default fmt subscriber is the same as env logger，the output code is:
> > https://github.com/tokio-rs/tracing/blob/master/tracing-subscriber/src/fmt/fmt_subscriber.rs#L696
> > It is still recommended to implement a subscriber by yourself
> 
> What about https://github.com/matter-labs/zksync/blob/master/core/lib/vlog/src/lib.rs ?

This is the default implementation of the fmt subscriber which I said

**Comment by silathdiir** [comment]
Hi, I am trying to look into this issue. After some investigation, I found a crate [tracing-appender](https://github.com/tokio-rs/tracing/tree/master/tracing-appender) (as a part of [tokio-rs/tracing](https://github.com/tokio-rs/tracing)). There is an example of [Non-Blocking Writer](https://github.com/tokio-rs/tracing/tree/master/tracing-appender#non-blocking-writer) as below (I am sorry that I haven't reviewed the source code of this crate for details):

```
impl std::io::Write for TestWriter {
  ...
}

fn main() {
    let (non_blocking, _guard) = tracing_appender::non_blocking(TestWriter);
    tracing_subscriber::fmt().with_writer(non_blocking).init();
}
```

Should we use this crate to create a non-block log writer directly (with crate `tokio-rs/tracing`)? Or follow it to create a custom non-block writer? What's your opinion? Thanks.

**Comment by HAOYUatHZ** [comment]
> Should we use this crate to create a non-block log writer directly (with crate `tokio-rs/tracing`)?

I think that's a great idea. ;D
