### ISSUE TITLE
bug: symbol resolving is incorrect

### ISSUE THREAD

**Issue by HAOYUatHZ** [Fluidex/dingir-exchange#122]
As discussed in https://github.com/Fluidex/tmp_frontend/issues/61#issuecomment-810803680

+ https://github.com/Fluidex/dingir-exchange/blob/50da807e2c3652f6a2a7f0ec2090f4c63e88ade6/src/restapi/tradingview.rs#L174
+ https://github.com/Fluidex/dingir-exchange/blob/50da807e2c3652f6a2a7f0ec2090f4c63e88ade6/src/restapi/tradingview.rs#L279

look incorrect (forgetting to throw away the 'exchange:' prefix)

Returning a full_name identical to name is a temp fix :https://github.com/Fluidex/dingir-exchange/commit/749cd0bc5224746d60fb8b7aedc9365232a5a88b

But we still prefer returning a full_name with exchange prefix, to comfort the standard.

**Comment by noel2004** [comment]
I will look into it
