### ISSUE TITLE
list internal transfer txs

### ISSUE THREAD

**Issue by HAOYUatHZ** [Fluidex/dingir-exchange#165]
we need to add an API to list all txs for internal transfer

stage 1: we query from DB

stage 2: we cache for every 2 minutes.

---

to query from DB we need to desgin a DB schema

and we need to persist TRANSFER_MSG (not just OPERATION_LOG_TRANSFER) into DB

**Comment by HAOYUatHZ** [comment]
> to query from DB we need to desgin a DB schema
> and we need to persist TRANSFER_MSG (not just OPERATION_LOG_TRANSFER) into DB

I've finished adding DB schema and MQ. we can start adding API now

**Comment by lispc** [comment]
why cache? And the i think the request should be 

```
struct Request {
  user: string, // can this field be empty to return all inner transfers?
  transfer_from_only: bool, default false
  transfer_to_only: bool, default fasle. the above two fileds cannot be false both.
}
```

or 

```
struct Request {
   from_account: string,
   to_account: string,
   cond: 'and' | 'or' // select * from transfer where from = $from_account and/or to = $to_account
}
```

// of source paging needed, limit/offset/page etc
// maybe from_time / to_time can also be added

**Comment by HAOYUatHZ** [comment]
Binance doesn't have this API https://binance-docs.github.io/apidocs/spot/

we need to design by our own

**Comment by HAOYUatHZ** [comment]
After discussions, we may define the APIs as:

+ /deposit-history?filter=L1&start=XXXX&limit=XXX
+ /deposit-history?filter=L2&start=XXXX&limit=XXX
+ /withdrawal-history?filter=L1&start=XXXX&limit=XXX
+ /withdrawal-history?filter=L2&start=XXXX&limit=XXX

**Comment by HAOYUatHZ** [comment]
duplicated in https://github.com/Fluidex/dingir-exchange/issues/246
