### ISSUE TITLE
bug: use rounded up value for amount & price in commit_order

### ISSUE THREAD

**Issue by HAOYUatHZ** [Fluidex/dingir-exchange#212]
In frontend and https://github.com/Fluidex/dingir-exchange/blob/master/examples/js/client.ts#L95-L96 we use rounded -up value for amount&price.

But in https://github.com/Fluidex/dingir-exchange/blob/master/src/matchengine/asset/asset_manager.rs#L71 we don't round up the values.

This needs to be consistent for calculating order_hash and verifying the signature.

Usually it will be okay, but sometimes it's buggy.

**Comment by lispc** [comment]
No. Backend rejects order with wrong precision.

https://github.com/Fluidex/dingir-exchange/blob/master/src/matchengine/market/mod.rs#L169-L178

**Comment by lispc** [comment]
ok i see. checking sig before checking precision gives misleading/confusing error msg.

**Comment by HAOYUatHZ** [comment]
> ok i see. checking sig before checking precision gives misleading/confusing error msg.

You are right. Your description is more accurate.

**Comment by HAOYUatHZ** [comment]
For rounding. refer to:
+ https://github.com/Fluidex/dingir-exchange/blob/master/src/matchengine/market/mod.rs#L171
+ https://github.com/Fluidex/dingir-exchange/blob/master/src/matchengine/market/mod.rs#L175

**Comment by HAOYUatHZ** [comment]
In conclusion:

+ check precision before validate signature
+ fix OrderCommitment::hash() logic: adding rounding
