### ISSUE TITLE
sqlx batch insert

### ISSUE THREAD

**Issue by lispc** [Fluidex/dingir-exchange#25]

**Comment by noel2004** [comment]
After digging in some code inside sqlx I find:

1. The common pattern in the protocol flow for a "batch" action like insert should like this:
      
       ` [Parse] -> ([Bind] -> [Execute]) *[repeat many times until limit] -> [Sync]`

1. We have no luck that currently the driver of sqlx always apply a `sync` after `execute` command so it waste too many time in round-trips. So the alleviate way seems like this:

    + Prepare for a huge query which insert many lines, like `insert into my_table value ($1, $2), ($3, $4), ....`, (should persist the query for more efficiency?)
    + Then send all arguments in another huge `Bind` message, then `Execute` and `Sync`.

1. Some issues may leave like caring about the size limit of message and how/whether to cache prepared query (with different size for inserting objects). Should be trivial.

1. Or we can just fork and hack the sqlx-core for a new pgsql driver which support batching? This is not so hard base on current code, but ...

**Comment by lispc** [comment]
I think even unprepared statement is enough for a while.
