### ISSUE TITLE
add signature to transfer

### ISSUE THREAD

**Issue by HAOYUatHZ** [fluidex/dingir-exchange#270]
1. [x] add signature to matchengin protobuf `TransferRequest` (similar to `OrderPutRequest`)
2. [x] add `signature` field to `models::InternalTx` (like in `models::OrderHistory`), which will further be sent to MQ.
3. [x] dump new test_unify_message.txt
4. [ ] process new test_unify_message.txt in rollup_state_manager

**Comment by stevenatcrypto** [comment]
Please reopen this issue, will continue on remaining three tasks.
