### ISSUE TITLE
corrupted DB when migrations fail (starting persistor before matchengine)

### ISSUE THREAD

**Issue by lackrobin** [fluidex/dingir-exchange#356]
The error occures in an orchestrated environment, i guess when the orchestrator decides to restart pods in a certain order. i think if the persistor is started before the matchengine the error occures and the migrations fail. also the database seems to be corrupt from this point forward, since the only solution is to reset the DB. 

`[0m fluidex_common::non_blocking_tracing: thread 'main' panicked at 'Init state error: migration 20200123090258 was previously applied but has been modified', src/bin/matchengine.rs:30:38`

**Comment by HAOYUatHZ** [comment]
I think it would be better if we separate this issue into 2 sub-problems.

1. fix the migration problem (#357 ).
2. fix the "needing to reset the db" problem.
3. will be better if restapi retries until connecting to matchengine

## context
https://github.com/fluidex/dingir-exchange/issues/244#issuecomment-953683939

**Comment by HAOYUatHZ** [comment]
Hi @lackrobin @gcomte 

So can we close this issue now?

**Comment by lackrobin** [comment]
We tested it in a cluster and it seems to be fixed 👍
