### ISSUE TITLE
Need to update document

### ISSUE THREAD

**Issue by jabethtoday** [fluidex/dingir-exchange#375]
hi all,
I've tried follow readme file to start but this command `npx ts-node trade.ts` not found trade.ts. 
I'm also tried with python example but when run `python put_order.py` i got error 

```
        debug_error_string = "{"created":"@1641810269.581794000","description":"Error received from peer ipv4:127.0.0.1:50051","file":"src/core/lib/surface/call.cc","file_line":1075,"grpc_message":"invalid signature","grpc_status":3}"
```

Can you take notes something (or update document) to help newbie get started. Thank you.

**Comment by gcomte** [comment]
Thanks for the quick merge @HAOYUatHZ 

@jabethtoday: I wrote a small document that has some additional information on how to get started with dingir-exchange: https://github.com/gcomte/dingir-exchange-docs

**Comment by jabethtoday** [comment]
Many thanks, your good job and fast reply.  Best wishes for you
