### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by vahidalvandi** [Fluidex/dingir-exchange#383]
Hello, thank you for publishing this project
I have been researching digital currency exchange for some time and I really do not know where to start. I am more interested in working with Python and need guidance on what the database structure and data type should look like. Thanks for taking the time to guide me.

**Comment by 0xmountaintop** [comment]
database structure and data type depends on your design.

anyway you can start by looking into dingir-exchange code

**Comment by vahidalvandi** [comment]
I have same questions, thank you for answering me with patience.

Why should we use rust? Was not python or go more appropriate?

**Comment by 0xmountaintop** [comment]
You can use python or go.

We use rust because we like the safety it offers without losing performace.

**Comment by vahidalvandi** [comment]
I'm also looking for a better option than go or python.
I have a question about exchange architecture can I ask here?

**Comment by 0xmountaintop** [comment]
Feel free to join our telegram: https://t.me/fluid_dex

**Comment by vahidalvandi** [comment]
I asked my questions in the telegram
