### ISSUE TITLE
Improvment: towards a full async database.rs module

### ISSUE THREAD

**Issue by noel2004** [Fluidex/dingir-exchange#47]
With the inducing of sqlx, db operations have obtained a async fashion while the database.rs module still stuck to the sync code, applying separated threads for inserting data. I have purposed a refactoring which respecting the original designation, and turn the whole code into fully async fashions as following:

+ A tokio-mpsc channel would be used to replace the cross_beam channel, which carry 3 types of messages: 

     + Data: an data object which would be inserted to db
     + TaskDone: a notification that an inserting task has done. There is no notification for task failure because inserting task must retry and resolve any issue it has encountered by itself.
     + Exit: the exit flag for a totally shutdown

+ An extra scheduler task is induced, it maintain a data cache, which is vector for a series data object, and a counter for the number of activating tasks. It act as the single consumer of the mpsc channel. It consider a limit LN for the maximum of task, and work as following:

    (for a current state [V, N] with cached data objects in vector V and N activating tasks)
     * On data: if N < LN spawn another inserting task for V, V <- Null, N <- N + 1; else V <- flat([V, data])
     * On TaskDone: if V is not Null spawn another inserting task for V, V <- Null; else N <- N - 1;
     * On Exit: wait for finish of current tasks and exit;

+ In the append method of DatabaseWriter, it produce a data message for the mpsc channel;

+ When an spawned task finished, it produce a TaskDone message for the mpsc channel;

**Comment by noel2004** [comment]
Not really a great changes to current code. Work should be done within 4-6 hrs

**Comment by HAOYUatHZ** [comment]
closed via #52
