### ISSUE TITLE
feature: get trades of order API

### ISSUE THREAD

**Issue by lispc** [Fluidex/dingir-exchange#49]
https://www.reddit.com/r/BinanceExchange/comments/e7kzht/binance_api_get_order_trades/

req: /{market}/{order_id}

resp: {trades: [{ time, amount, price, quote_amount, fee} ]}

Use the trade history table

**Comment by noel2004** [comment]
Should the "volume" field is the accumulated amount of trades?

**Comment by HAOYUatHZ** [comment]
Yes. but in base.

**Comment by lispc** [comment]
> Should the "volume" field is the accumulated amount of trades?

yes

**Comment by HAOYUatHZ** [comment]
seems both of them are just for 1 trade @lispc? amount in BASE and volume in QUOTE

**Comment by lispc** [comment]
changed to quote_amount
