### ISSUE TITLE
refactor: use oneshot::channel to refactor controller & server

### ISSUE THREAD

**Issue by lispc** [Fluidex/dingir-exchange#51]
First, add a rwlock inside every market and balance_manager ( std::sync::rwlock or tokio::sync::rwlock ? we have (num of markets + 1) rwlocks in total ). Then add a main loop inside controller, this loop will handle all the write apis and persistent timer.

server.rs:
```
  async fn handle_read_api(req):
           acquire related rwlock;
           resp = calculate();
           return
  async fn handle_write_api(req):
     let (sender, receiver) = oneshot::channel();
     global_task_queue.push((req, sender));
     let resp = receiver.recv()
     return resp
```

controller.rs:
```
while(true) {
   let task = select { api_queue , persistent_timer } ;
   if let RpcReq(req, sender) = task {
     let resp = handle(req);
     sender.send(resp);
  } else {
     // timer;
     fork; 
     if child process { persistent state };
   }
}
```

After this refactor, I will we can remove all the unsafe global pointer ( *Controller ). And read api can be process parallel ( partially ) .  And also remove the "stop world debug task" magic.

**Comment by lispc** [comment]
Maybe this issue can be split into two parts first just a the global loop second use rwlock to make read api parallel

**Comment by lispc** [comment]
A global rwlock seems enough for a while

**Comment by noel2004** [comment]
oneshot channel can be used for only once (and passing a single message). Guess we should use mpsc channel here?

**Comment by lispc** [comment]
> oneshot channel can be used for only once (and passing a single message). Guess we should use mpsc channel here?

the above pattern is widely used in golang & rust community.  I think that is ok

**Comment by lispc** [comment]
Suggest development based on <https://github.com/Fluidex/dingir-exchange/pull/39>.

**Comment by noel2004** [comment]
> Suggest development based on #39.

ok, I have merged `feature/zzhang/tokio_v1` branch into my workspace and start on it
