### ISSUE TITLE
unify date formats

### ISSUE THREAD

**Issue by lispc** [fluidex/dingir-exchange#58]
create_at of active orders is unix timesamp,   
while create_at of closed orders is rfc3399 string.    
We should make them consistent later

**Comment by lispc** [comment]
https://github.com/Fluidex/dingir-exchange/blob/master/examples/js/print_orders.js    can be used for demo this

**Comment by lispc** [comment]
// you have to revert this commit to test locally on win

https://github.com/Fluidex/dingir-exchange/commit/c4b2aa3c48056e9eef228ba1718ef40fecf9882d

**Comment by HAOYUatHZ** [comment]
closed in https://github.com/fluidex/dingir-exchange/pull/359
