### ISSUE TITLE
bug: 'taker_side's in recenttrades are all BID 

### ISSUE THREAD

**Issue by lispc** [Fluidex/dingir-exchange#63]
Running node tick.js for a while, then fetch results of recenttrades API, you will see every trade's taker_side is BID.  Seems something wrong happend.

( I think the bug is introduced within last serveral commits )

**Comment by noel2004** [comment]
ok, I will track it

**Comment by noel2004** [comment]
Following is my discovery:

1. tick.js send a pair of ask/bid order with the same price and amount so they should be matched and form a trade
2. the ask order is put first then the bid order, so in the trade, the ask_order_id is smaller than the bid_order_id
3. persistor turn a trade message into a trade_record entry, with following code to decide taker_side:

```rust
if origin.ask_order_id < origin.bid_order_id {
                OrderSide::BID
            } else {
                OrderSide::ASK
            },
```

As the result, all entries in trade_record has a bid taker side.

When I make bid order first in ticker.js, I would query all trade's with taker_side which is ASK.

Maybe we should randomize the sequence of ordering in ticker.js ?

**Comment by HAOYUatHZ** [comment]
seems so.   maybe just randomly decide on using ORDER_SIDE_ASK or ORDER_SIDE_BID

**Comment by lispc** [comment]
I see. The earlier version running on the server used randomized price too.  But it seems i stashed  the diff and forgot commiting.  I will handle this problem

**Comment by lispc** [comment]
No are u sure tick.js send a pair of ask/bid order with the same price and amount？if so，maybe my rand float function does not work correctly

**Comment by noel2004** [comment]
sorry, I missed the meaning of getRandomFloatAround.

But I do see trade marked as ASK from restapi after reverse the order of BID and ASK.

**Comment by noel2004** [comment]
I also encounter "balance is not enough" issue. Guess if the engine has stacked some order before, it would be easy to produce a fully ASK/BID trade record list.

**Comment by HAOYUatHZ** [comment]
> maybe my rand float function does not work correctly

I just test it. getRandomFloatAround seems working correctly on my machine

**Comment by noel2004** [comment]
> > maybe my rand float function does not work correctly
> 
> I just test it. getRandomFloatAround seems working correctly on my machine

And still fully BID trade list? Anyway, I found it should be caused by the emitted trades always include a ask_order_id less than the bid_order_id. That is, matchengine keep matching recent bid to a earlier ask order. I think it is because of a stacked ask orders by some reason, or some occasion due to the complexing of a series of randomize.

**Comment by HAOYUatHZ** [comment]
Seems we can close this issue now?

**Comment by lispc** [comment]
Yes
