### ISSUE TITLE
find a tool to generate API swagger automatically 

### ISSUE THREAD

**Issue by lispc** [fluidex/dingir-exchange#65]
or use openapi/swagger to generate codes...

**Comment by HAOYUatHZ** [comment]
+ https://paperclip.waffles.space/actix-plugin.html
+ https://github.com/kdy1/rweb/blob/master/examples/openapi.rs

**Comment by HAOYUatHZ** [comment]
closed by https://github.com/fluidex/dingir-exchange/pull/305?

**Comment by HAOYUatHZ** [comment]
A few things to be done:

1. how to serve swagger?
2. reorg different services' paths

**Comment by HAOYUatHZ** [comment]
> A few things to be done:
> 
> 1. how to serve swagger?
> 2. reorg different services' paths

closed by https://github.com/fluidex/orchestra/pull/10
