### ISSUE TITLE
fix: add Kafka health check when starting server

### ISSUE THREAD

**Issue by HAOYUatHZ** [Fluidex/dingir-exchange#7]
When starting server, we choose to panic if the connection to PG fails, but we doesn't check Kafka's status and only log error for kafka later.

We'd better also add such a check -- we probably should panic if fail to connect to Kafka.

**Comment by noel2004** [comment]
Currently the code in controller.rs has unwrapped the Result<KafkaMessageSender> (line 49) but it will not panic because the creation of low-layer client will be always success even for a broken connection.

The low-layer Kafka client do not consider the connection error as fatal (the client would just retry for a successful connection) when being created. In fact, in the native layer (the rdkafka), all the error is notified by a callback function so even if we have some way to panic, it may panic at any time instead of the moment of creation.

**Comment by HAOYUatHZ** [comment]
> Currently the code in controller.rs has unwrapped the Result (line 49) but it will not panic because the creation of low-layer client will be always success even for a broken connection.
> 
> The low-layer Kafka client do not consider the connection error as fatal (the client would just retry for a successful connection) when being created. In fact, in the native layer (the rdkafka), all the error is notified by a callback function so even if we have some way to panic, it may panic at any time instead of the moment of creation.

Yes I don't mean that we should treat connection error as fatal, and I agree with you that we can handle this at any time.

IMO I prefer checking Kafka at the begining (and panic if we need to), because we may forget to run Kafka service. However, after getting the server running, we should probably only log error instead of panicking, for server robustness/availability purpose.

**Comment by noel2004** [comment]
> IMO I prefer checking Kafka at the begining (and panic if we need to), because we may forget to run Kafka service. However, after getting the server running, we should probably only log error instead of panicking, for server robustness/availability purpose.

I guess it is enough to do the first checking by perform some action (like fetchmetadata)  on the client just being created. Just like what has done in the health check code in the kline feature?

**Comment by HAOYUatHZ** [comment]
> > IMO I prefer checking Kafka at the begining (and panic if we need to), because we may forget to run Kafka service. However, after getting the server running, we should probably only log error instead of panicking, for server robustness/availability purpose.
> 
> I guess it is enough to do the first checking by perform some action (like fetchmetadata) on the client just being created. Just like what has done in the health check code in the kline feature?

This can be an approach. I might think about how to organize the codes in a better way later.

**Comment by HAOYUatHZ** [comment]
close via https://github.com/Fluidex/dingir-exchange/pull/45
