### ISSUE TITLE
load asset and market from database

### ISSUE THREAD

**Issue by lispc** [Fluidex/dingir-exchange#77]
Currently the matchengine server loads available assets and trading pairs ( like ETH/USDT ) from the config.yaml file when it starts.    

We should load these information from db.

1. add a new table named `market`. The schema of this table is similar to Market in src/config.rs, with several new columns: id ( auto incremental ), create_time. Also add a table "asset", schema similar to Asset in src/config.rs
2. add migration sqls into migrations dir. Both the schema sql and data sql ( like migrations/mock ) are needed . Run the migrations when server starts.
3. loading the data in these two tables when server starts

**Comment by HAOYUatHZ** [comment]
closed via #85

**Comment by HAOYUatHZ** [comment]
closed via #85
