### ISSUE TITLE
feature: add trade id in ordertrades API

### ISSUE THREAD

**Issue by lispc** [Fluidex/dingir-exchange#82]
src/restapi/public_history.rs

fn order_trades

return result like this

struct XX {
    pub time: TimestampDbType, // it will be rfc3399 string in the resp json. 
    pub trade_id: i64, // the id in user trades table , needed by frontend
    pub price: DecimalDbType, //  it will be string in the resp json
    pub amount: DecimalDbType,
    pub quote_amount: DecimalDbType,
    pub fee: DecimalDbType,
}

**Comment by HAOYUatHZ** [comment]
closed via https://github.com/Fluidex/dingir-exchange/pull/83

we may need more fine-grained fix
