### ISSUE TITLE
unuseful codes in matchengine

### ISSUE THREAD

**Issue by HAOYUatHZ** [Fluidex/dingir-exchange#86]
https://github.com/Fluidex/dingir-exchange/blob/ac4ae2e84da69cde7b972eeb04dc20391cb53648/src/bin/matchengine.rs#L44-L46

this seems unuseful?

**Comment by noel2004** [comment]
Yes. Will erase them when completely remove the feature that loading market data from configure file

**Comment by HAOYUatHZ** [comment]
> Yes. Will erase them when completely remove the feature that loading market data from configure file

great!
