### ISSUE TITLE
fix hardcoded ETH_USDT in ./src/restapi/tradingview.rs

### ISSUE THREAD

**Issue by lispc** [Fluidex/dingir-exchange#93]
we need to support multi markets now. The hardcoded "ETH_USDT" should be fixed.  We should make a right API for frontend.

related: [UDF](https://zlq4863947.gitbook.io/tradingview/3-shu-ju-bang-ding/udf)

**Comment by noel2004** [comment]
Got it. Expect to finish in next 2-3 days.

**Comment by noel2004** [comment]
Well the API are highly involved with business. I should make things clear before working:

Are followng purpose correct (I have learn something from [here](https://github.com/serdimoa/charting) )?

1. for /config, currently we can just provide one symbols_types *btc* and should response like: `{"name": "cryptos", "value": "btc"}` . Also we can just provide an empty array for exchanges.

2. When resolving a symbol (/symbols), we first search the market record which market_name matching the symbol. If no record, parse the symbol by <base>_<quote> and search for the corresponding market.

3. Some fields of the returning [symbolinfo ](https://github.com/serdimoa/charting/blob/master/Symbology.md)maybe different to the currently hardcoded one: 
    * "timezone" is utc
    * "exchange" is "fluidex"
    * pick market_name for ticker if not null
    * calculate the pricescale and minmov from the Demical structure of minamount column
