### ISSUE TITLE
minor fix: avoid too much db error log ..

### ISSUE THREAD

**Issue by lispc** [Fluidex/dingir-exchange#94]
I find `loop { err := some_db_insert(); if err != nil { break } else { println(err) }` will generate too much logs and fill disk...

I think maybe at least we can sleep 100ms between two same db query? 

<https://github.com/Fluidex/dingir-exchange/blob/be5744f6d1a679ec74a75da74238db6ff33f5af1/src/storage/database.rs#L523>

**Comment by noel2004** [comment]
I guess most error encountered  here could not be recovered in a short interval so maybe we can sleep longer, like 1s?
